### ISSUE TITLE
Testing framework

### ISSUE THREAD

**Issue by kozmaz87** [bbc/ebu-tt-live-toolkit#21]
We need test framework set up with pytest and pytest-bdd.

**Comment by kozmaz87** [comment]
There is a discussion topic about this regarding the consumer logic and the way to consistently test it but make is still usable and legible and is relatively easy to extend with BDD. @nigelmegitt your input would be highly appreciated.

My initial thoughts are: Gherkin and BDD are cool but it is getting very lengthy when it comes to describe the complex nature of our timing problems. The number of GIVEN lines would be in the dozens and then the THEN lines would be something similar but not much less than the GIVEN lines in case we stick to the book and describe every scenario with full granularity in respect of what the timing values are on which element in our scenario. I think the other extreme and therefore the other end of this spectrum is providing the ultra high-level income and outcome data suite in which case we cannot really take advantage of gherkin as much as I would like.

I am still doing my homework researching if there was someone who came up with an aurea mediocritas here. We might be able to provide some test sets and modify some elements via BDD to make the adjustments to modify the scenario's context. For example we have 5 documents with 1 second intervals and we call this test set 1 the scenario might look something like:
GIVEN test set 1
AND <xpath to attribute/element we would like to replace> is <replacement>
...
WHEN processed for archiving purposes/live presentation
AND sequenceNumber=1 received at <timecode>
...
THEN <and here comes some way of defining the outcome to the required complexity but still giving ourselfes the granularity to be able to afford testing it in Gherkin>

In any way I will consult with Daniel from BBC Scotland. He was helping me out when I investigated python and bdd frameworks. They did a project there where they used this method of testing and I wonder if they ran into the same complexity issue.

My impression is that bdd covers well the point, click and input user-journey scenarios but I am yet to understand if the method can cover our usecase of data processing nodes/pipelines. Maybe in that case this isn't the right approach no matter how much I would like to see us implement something as descriptive for the non-technical user as possible via Gherkin language.

**Comment by kozmaz87** [comment]
The following conversation helps:
`

daniel [3:06 PM] 
The compromise is to use scenario examples. You can be expressive and concise while covering a lot of cases. Let me see if I can find a good example

zoltan.kozma [3:07 PM] 
I have come up with something intuitively, which seems to be similar to what you are describing

[3:08] 
GIVEN test set 1
AND (xpath to attribute/element we would like to replace) is (replacement)
...
WHEN processed for archiving purposes/live presentation
AND sequenceNumber=1 received at (timecode)
...
THEN (and here comes some way of defining the outcome to the required complexity but still giving ourselfes the granularity to be able to afford testing it in Gherkin)

[3:10] 
So this uses a common set of base documents providing all the from the timing point of view unnecessary details and a number of dummy documents and I would think of trying to manipulate them using minimal number of steps to achieve the anomaly I am trying to cover

daniel [3:12 PM] 
Got an idea, 2 seconds...

new messages
daniel [3:18 PM] 
```

[3:18] 
 ```Scenario Outline: Subtitles
    Given an original document #document template loaded from file
    And the document has a sequence of <sequence> #manipulate the template with xpath
    And the document has a blah of <blah> #manipulate the template with xpath some more
    And the document has a blah2 of <blah> #manipulate the template with xpath some more
    And the document has a blah3 of <blah> #manipulate the template with xpath som more
    ...
    When the output is processed 
    Then the output document should match <expected_document>

    Examples:
    sequence     | blah     | blah1    | blah2   | expected_document
    1            | value    | value    | value   | path/to/expected/file1
    2            | value    | null    | value   | path/to/expected/file2
    3            | value    | value    | null      | path/to/expected/file3
```
(edited)

[3:20] 
Stuck the nulls in the table to highlight that you can have optional elements and just filter them out if they aren’t used in that scenario.

zoltan.kozma [3:20 PM] 
hm...

[3:20] 
this gives me an idea

[3:20] 
maybe I could use templating language and variable assignment to do this simpler

[3:20] 
that eliminates a sometimes painfully overcomplicated xpath expression

[3:21] 
but ultimately xpath has full capability of matching xml

[3:21] 
interesting tradeoff possibility

daniel [3:22 PM] 
Templating would be good. Your template might need to be modular though, if there are optional elements. Then you just build up your final document from the modular templates.

[3:22] 
Could probably even write a generic handler for `And the document has a blah of <blah>` that sticks the value in to the placeholder for `blah`

[3:24] 
As a potential user of your reference implementation, some modular templates, combined with gherkin specifying the values that are going in to those templates, and the expected output file, would be really useful.

zoltan.kozma [3:26 PM] 
There was a bit contradicting best practice tutorial that I read about this, which said: Try to cover the expected workflows with BDD, not your edge cases. I am not sure what it meant because this was a presentation for which probably a narration is necessary to get the full story. It may have referred to having to use lower level tooling to cover the crazy cases.... I am unsure

daniel [3:27 PM] 
Maybe, but the power of the examples block is that each new edge case is just another line in the table. I’ve always tried to cover at least some edge cases.

[3:29] 
I once had some scenario for sequential events, where a time threshold had to be met between events. I used an example block where the first column was the time of the first event, and each subsequent column was the offset from that time, with the last column being the expected end state.

[3:30] 
Worked really well. Covered plenty of happy and edge cases in a 30 line gherkin file.

[3:30] 
Was really expressive and easy to comprehend.

[3:32] 
I almost always use example blocks for any non-trivial scenario.
`

**Comment by nigelmegitt** [comment]
It seems like we've got far enough with the current testing framework that this can be closed - what do you think @kozmaz87 ?

**Comment by nigelmegitt** [comment]
We've had this testing framework in use for a while, and it's got around 1000 tests already. I think we're happy with it! Closing as done.
